require(data.table)
require(dplyr)
death<-fread('/infodev1/rep/projects/jason/deathtargets.csv')
demo<-fread('/infodev1/rep/projects/jason/demo.csv')
dia<-fread('/infodev1/rep/projects/jason/mydia.csv')
ahos<-fread('/infodev1/rep/projects/jason/admit_hos.csv')
dhos<-fread('/infodev1/rep/projects/jason/disch_hos.csv')
lab<-fread('/infodev1/rep/projects/jason/mylabs.csv')
pres<-fread('/infodev1/rep/projects/jason/mypres.csv')
serv<-fread("/infodev1/rep/projects/jason/myserv.csv")
surg<-fread("/infodev1/rep/projects/jason/newsurg.csv")
vital<-fread("/infodev1/rep/projects/jason/myvitals.csv")

